# Starter pipelines
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


  - task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $simpleBranchName = "$(System.PullRequest.TargetBranch)".Substring("refs/heads".length + 1)
      $refsBranchName = "origin/$simpleBranchName"
      $changedFiles = git diff $refsBranchName --name-only
     
      foreach ($file in $changedFiles) {
 Write-Host "Checking lint on: $sourceDirectory/$file"
    npm run lint "$sourceDirectory/$file"
    if ($? -eq $false) {
      [void]$errors.Add("Linting error on: $sourceDirectory/$file ");
    }

